Repository dafny-lang/dafny, pull requests merged in 2022-01, with the labels that each got.

#1691 Fixed specifications misclassified as compiled expressions
  Source/Dafny/AST/DafnyAst.cs
  Source/Dafny/Resolver.cs
  Source/Dafny/Util.cs
  Test/git-issues/git-issue-697h.dfy
  Test/git-issues/git-issue-697h.dfy.expect
Labels: bug

#1683 NullPointerException fixed in Parser
  Source/Dafny/Dafny.atg
  Test/git-issues/git-issue-1682.dfy
  Test/git-issues/git-issue-1682.dfy.expect
Labels: bug, parser, language server

#1698 Clearer Dafny's error messages about arguments being wrong, not parameters
  Source/Dafny/Resolver.cs
  Test/dafny0/AsIs-Resolve.dfy.expect
  Test/dafny0/BitvectorResolution.dfy.expect
  Test/dafny0/Coinductive.dfy.expect
  Test/dafny0/IteratorResolution.dfy.expect
  Test/dafny0/NewtypesResolution.dfy.expect
  Test/dafny0/ParameterResolution.dfy.expect
  Test/dafny0/ResolutionErrors.dfy.expect
  Test/dafny0/TypeTests.dfy.expect
  Test/dafny0/UserSpecifiedTypeParameters.dfy.expect
  Test/exceptions/TypecheckErrors.dfy.expect
  Test/ghost/DisallowedGhost1.dfy.expect
  Test/git-issues/git-issue-283g.dfy.expect
  Test/git-issues/git-issue-484.dfy.expect
  Test/git-issues/git-issue-750.dfy.expect
  Test/hofs/ResolveError.dfy.expect
Labels: error reporting

#1711 First refactoring to discharge a bit the Resolver.
  Source/Dafny/AST/DafnyAst.cs
  Source/Dafny/Resolver.cs
  Source/Dafny/Resolver/TypeConstraint.cs
Labels: resolution

#1712 Add CSV logger for test results and timing
  Source/Dafny/DafnyOptions.cs
  Source/DafnyDriver/BoogieXmlConvertor.cs
  Source/DafnyDriver/CSVTestLogger.cs
  Source/DafnyDriver/DafnyDriver.cs
  Test/logger/CSVLogger.dfy
Labels: enhancement, verification

#1759 Report timeouts in IDE to fix #1710
  Source/DafnyLanguageServer.Test/Various/CompilationStatusNotificationTest.cs
  Source/DafnyLanguageServer/Language/DafnyProgramVerifier.cs
Labels: language server

#1716 Changes in Python compiler to successfully pass the test comp/Hello.dfy.
  Source/Dafny/Compilers/Compiler-python.cs
  Source/DafnyRuntime/DafnyRuntime.py
  Test/comp/Hello.dfy
  Test/comp/Hello.dfy.expect
  Test/comp/IKnowThisMuchIs.dfy
  Test/comp/IKnowThisMuchIs.dfy.expect
Labels: compiler
