Repository dafny-lang/dafny, pull requests merged in 2022-05, with the labels that each got.

#2079 fix: calc of multiset crashes
  RELEASE_NOTES.md
  Source/Dafny/Dafny.atg
  Source/DafnyLanguageServer.Test/Various/CompilationStatusNotificationTest.cs
  Test/git-issues/git-issue-1682.dfy.expect
Labels: bug, parser

#2088 chore: Better documentation about set comprehension of allocated objects
  docs/DafnyRef/Expressions.md
Labels: bug, documentation

#2091 chore: Remove unused field ResolvedUpdateExpr of SeqUpdateExpr
  Source/Dafny/AST/DafnyAst.cs
  Source/Dafny/AST/Printer.cs
  Source/Dafny/Compilers/SinglePassCompiler.cs
  Source/Dafny/Substituter.cs
  Source/Dafny/Triggers/TriggerExtensions.cs
  Source/Dafny/Verifier/Translator.ExpressionTranslator.cs
  Source/Dafny/Verifier/Translator.cs
Labels: clean-up

#2090 chore: Testing whitespace
  .github/workflows/test-report.yml
  Source/Dafny/Reporting.cs
  Source/XUnitExtensions/AssertWithDiff.cs
Labels: run-deep-tests

#1942 feat: Verification diagnostics (core version)
  RELEASE_NOTES.md
  Source/Dafny/Dafny.atg
  Source/DafnyLanguageServer.Test/DafnyLanguageServer.Test.csproj
  Source/DafnyLanguageServer.Test/Diagnostics/LinearRenderingTest.cs
  Source/DafnyLanguageServer.Test/Diagnostics/LinearVerificationDiagnosticTester.cs
  Source/DafnyLanguageServer.Test/Diagnostics/SimpleLinearVerificationDiagnosticTester.cs
  Source/DafnyLanguageServer.Test/Unit/TextDocumentLoaderTest.cs
  Source/DafnyLanguageServer.Test/Util/AssertWithDiff.cs
  Source/DafnyLanguageServer.Test/Various/CompilationStatusNotificationTest.cs
  Source/DafnyLanguageServer.Test/Various/SlowVerifier.cs
  Source/DafnyLanguageServer/DafnyRequestNames.cs
  Source/DafnyLanguageServer/Language/BoogieExtensions.cs
  Source/DafnyLanguageServer/Language/DafnyProgramVerifier.cs
  Source/DafnyLanguageServer/Language/IProgramVerifier.cs
  Source/DafnyLanguageServer/Language/IVerificationProgressReporter.cs
  Source/DafnyLanguageServer/Language/SyntaxTreeVisitor.cs
  Source/DafnyLanguageServer/Language/VerifierOptions.cs
  Source/DafnyLanguageServer/README.md
  Source/DafnyLanguageServer/Workspace/ChangeProcessors/IRelocator.cs
  Source/DafnyLanguageServer/Workspace/ChangeProcessors/Relocator.cs
  Source/DafnyLanguageServer/Workspace/DafnyDocument.cs
  Source/DafnyLanguageServer/Workspace/DiagnosticPublisher.cs
  Source/DafnyLanguageServer/Workspace/DocumentDatabase.cs
  Source/DafnyLanguageServer/Workspace/IDiagnosticPublisher.cs
  Source/DafnyLanguageServer/Workspace/ITextDocumentLoader.cs
  Source/DafnyLanguageServer/Workspace/LanguageServerExtensions.cs
  Source/DafnyLanguageServer/Workspace/Notifications/VerificationDiagnosticsParams.cs
  Source/DafnyLanguageServer/Workspace/TextDocumentLoader.cs
  Source/DafnyLanguageServer/Workspace/VerificationProgressReporter.cs
Labels: kind: enhancement, part: lsp

#1944 feat: Verification diagnostics reordering
  RELEASE_NOTES.md
  Source/DafnyLanguageServer.Test/Diagnostics/LinearVerificationDiagnosticTester.cs
  Source/DafnyLanguageServer.Test/Diagnostics/ListeningTextDocumentLoader.cs
  Source/DafnyLanguageServer.Test/Diagnostics/ReorderingVerificationDiagnosticTester.cs
  Source/DafnyLanguageServer.Test/Synchronization/DiagnosticsTest.cs
  Source/DafnyLanguageServer/Workspace/ChangeProcessors/IRelocator.cs
  Source/DafnyLanguageServer/Workspace/ChangeProcessors/Relocator.cs
  Source/DafnyLanguageServer/Workspace/DafnyDocument.cs
  Source/DafnyLanguageServer/Workspace/DocumentDatabase.cs
  Source/DafnyLanguageServer/Workspace/TextDocumentLoader.cs
  Source/DafnyLanguageServer/Workspace/VerificationProgressReporter.cs
Labels: kind: enhancement, part: lsp

#2143 chore: Better design for building verification gutter status icons
  Source/DafnyLanguageServer/Workspace/DiagnosticPublisher.cs
  Source/DafnyLanguageServer/Workspace/Notifications/VerificationDiagnosticsParams.cs
Labels: kind: cleanup, part: lsp

#2148 fix: Untitled documents get their verification diagnostics
  Source/DafnyLanguageServer.Test/DafnyLanguageServerTestBase.cs
  Source/DafnyLanguageServer.Test/Various/DiagnosticMigrationTest.cs
  Source/DafnyLanguageServer/Language/DiagnosticErrorReporter.cs
Labels: kind: bug, part: lsp, difficulty: easy

#2145 chore: Explained ghost inference
  docs/DafnyRef/Statements.md
  docs/DafnyRef/Topics.md
  docs/DafnyRef/Types.md
Labels: kind: enhancement, part: documentation

#2162 Added verification trees for constructors with default values
  Source/Dafny/Dafny.atg
  Source/DafnyLanguageServer.Test/GutterStatus/SimpleLinearVerificationGutterStatusTester.cs
  Source/DafnyLanguageServer/Workspace/VerificationProgressReporter.cs
Labels: kind: enhancement, part: lsp

#1946 feat: Verification diagnostics hover
  Source/DafnyLanguageServer.Test/GutterStatus/ConcurrentLinearVerificationGutterStatusTester.cs
  Source/DafnyLanguageServer.Test/GutterStatus/LinearVerificationGutterStatusTester.cs
  Source/DafnyLanguageServer.Test/GutterStatus/SimpleLinearVerificationGutterStatusTester.cs
  Source/DafnyLanguageServer.Test/Lookup/HoverVerificationTest.cs
  Source/DafnyLanguageServer.Test/Unit/TextDocumentLoaderTest.cs
  Source/DafnyLanguageServer.Test/Util/ClientBasedLanguageServerTest.cs
  Source/DafnyLanguageServer/Handlers/DafnyHoverHandler.cs
  Source/DafnyLanguageServer/Handlers/DafnyTextDocumentHandler.cs
  Source/DafnyLanguageServer/Workspace/ChangeProcessors/IRelocator.cs
  Source/DafnyLanguageServer/Workspace/ChangeProcessors/ITextChangeProcessor.cs
  Source/DafnyLanguageServer/Workspace/ChangeProcessors/Relocator.cs
  Source/DafnyLanguageServer/Workspace/ChangeProcessors/TextChangeProcessor.cs
  Source/DafnyLanguageServer/Workspace/DafnyDocument.cs
  Source/DafnyLanguageServer/Workspace/DocumentDatabase.cs
  Source/DafnyLanguageServer/Workspace/IDocumentDatabase.cs
  Source/DafnyLanguageServer/Workspace/ITextDocumentLoader.cs
  Source/DafnyLanguageServer/Workspace/Notifications/VerificationDiagnosticsParams.cs
  Source/DafnyLanguageServer/Workspace/TextDocumentLoader.cs
  Source/DafnyLanguageServer/Workspace/VerificationProgressReporter.cs
Labels: kind: enhancement, part: lsp
