Repository dafny-lang/dafny, pull requests merged in 2022-02, with the labels that each got.

#1774 fix(lsp): Move timeout diagnostic test to Diagnostics.cs
  Source/DafnyLanguageServer.Test/Synchronization/DiagnosticsTest.cs
  Source/DafnyLanguageServer.Test/Various/CompilationStatusNotificationTest.cs
Labels: tests

#1821 chore: Fixing opaque documentation
  Source/Dafny/Rewriter.cs
  docs/Compilation/Boogie.md
  docs/DafnyRef/Attributes.md
  docs/DafnyRef/Types.md
Labels: documentation

#1831 fix: Use correct property to specify target framework in Coco.csproj
  third_party/Coco/src/Coco.csproj
Labels: clean-up

#1769 tests: Add an example to show how to interop Dafny and C#
  Source/IntegrationTests/LitTests.cs
  Test/lit.site.cfg
  Test/tutorial/Simple_compiler/.gitignore
  Test/tutorial/Simple_compiler/Compiler.dfy
  Test/tutorial/Simple_compiler/Compiler.dfy.expect
  Test/tutorial/Simple_compiler/Main.cs
  Test/tutorial/Simple_compiler/Makefile
  Test/tutorial/Simple_compiler/README.md
  Test/tutorial/Simple_compiler/Simple.g4
  Test/tutorial/Simple_compiler/SimpleCompiler.csproj
  Test/tutorial/Simple_compiler/example_input.calc
Labels: tests

#1865 fix(parser): Memory leak in RevealableTypeDeclHelper (closes #1858)
  Source/Dafny/AST/DafnyAst.cs
Labels: bug

#1864 fix(lsp): Memory leak in call to InferAndVerify (closes #1863)
  Source/Dafny/DafnyMain.cs
  Source/DafnyLanguageServer/Language/DafnyProgramVerifier.cs
  Source/DafnyTestGeneration/ProgramModification.cs
Labels: bug, language server
