Repository dafny-lang/dafny, pull requests merged in 2022-04, with the labels that each got.

#1971 Attribute FilledInDuringResolution added
  Source/Dafny/AST/DafnyAst.cs
Labels: clean-up

#2003 chore: Dafny Server documentation
  docs/DafnyRef/UserGuide.md
Labels: enhancement, documentation

#1985 Feat: Added ranges to expression
  RELEASE_NOTES.md
  Source/Dafny/AST/DafnyAst.cs
  Source/Dafny/Verifier/Translator.ExpressionTranslator.cs
  Source/Dafny/Verifier/Translator.TrStatement.cs
  Source/Dafny/Verifier/Translator.cs
  Source/DafnyLanguageServer.Test/Synchronization/DiagnosticsTest.cs
  Source/DafnyLanguageServer/Language/DafnyProgramVerifier.cs
Labels: enhancement, error reporting

#1981 Added debugging documentation for when verification is slow.
  docs/DafnyRef/UserGuide.md
Labels: enhancement, documentation

#2044 fix: Protect newtypes and datatypes from refinement
  RELEASE_NOTES.md
  Source/Dafny/AST/DafnyAst.cs
  Source/Dafny/Dafny.atg
  Source/Dafny/DafnyMain.cs
  Source/Dafny/RefinementTransformer.cs
  Test/dafny0/Modules0.dfy
  Test/git-issues/git-issue-1180a.dfy
  Test/git-issues/git-issue-1180a.dfy.expect
  Test/git-issues/git-issue-1180b.dfy
  Test/git-issues/git-issue-1963a.dfy
  Test/git-issues/git-issue-1963a.dfy.expect
  Test/git-issues/git-issue-1963b.dfy
  Test/git-issues/git-issue-1963b.dfy.expect
  Test/git-issues/git-issue-1963c.dfy
  Test/git-issues/git-issue-1963c.dfy.expect
  Test/git-issues/git-issue-852.dfy
Labels: soundness

#2059 fix: Use correct type for let expression generated by datatype update
  RELEASE_NOTES.md
  Source/Dafny/Resolver.cs
  Test/git-issues/git-issue-1479.dfy
  Test/git-issues/git-issue-1479.dfy.expect
Labels: soundness

#2014 Document converting an array to a sequence
  docs/DafnyRef/Types.md
Labels: documentation
