Repository dafny-lang/dafny, pull requests merged in 2022-03, with the labels that each got.

#1867 chore: Added favicon to Dafny documentation
  docs/_includes/head.html
  docs/_site/assets/dafny-favicon.png
Labels: documentation

#1883 chore: Make favicon to appear
  docs/DafnyRef/README.md
  docs/_includes/head.html
  docs/dafny-favicon.png
Labels: bug, documentation

#1894 Allow users to plug in custom compilers
  Source/Dafny/AST/DafnyAst.cs
  Source/Dafny/Compilers/Compiler-Csharp.cs
  Source/Dafny/Compilers/Compiler-cpp.cs
  Source/Dafny/Compilers/Compiler-go.cs
  Source/Dafny/Compilers/Compiler-java.cs
  Source/Dafny/Compilers/Compiler-js.cs
  Source/Dafny/Compilers/Compiler-python.cs
  Source/Dafny/Compilers/SinglePassCompiler.cs
  Source/Dafny/DafnyOptions.cs
  Source/Dafny/Plugin.cs
  Source/Dafny/Plugins/Compiler.cs
  Source/Dafny/Plugins/PluginConfiguration.cs
  Source/Dafny/Plugins/Rewriter.cs
  Source/Dafny/Resolver.cs
  Source/DafnyDriver/DafnyDriver.cs
  Source/DafnyLanguageServer.Test/Various/PluginsAdvancedTest.cs
  Source/DafnyLanguageServer.Test/Various/PluginsTest.cs
  Source/DafnyLanguageServer.Test/Various/PluginsTestBase.cs
  Source/DafnyPipeline.Test/PluginsTest.cs
  docs/DafnyRef/UserGuide.md
Labels: enhancement

#1872 docs: Document the -out compiler parameter
  docs/DafnyRef/UserGuide.md
Labels: documentation

#1876 fix(translator): Strip type constraints before generating rank axioms
  RELEASE_NOTES.md
  Source/Dafny/Verifier/Translator.DataTypes.cs
  Test/git-issues/git-issue-1875.dfy
  Test/git-issues/git-issue-1875.dfy.expect
Labels: bug, verification

#1814 Put Dafny options first and fix indentation in `Dafny /?`
  Source/Dafny/DafnyOptions.cs
Labels: documentation

#1930 Chore: More assertions explained
  docs/DafnyRef/Expressions.md
  docs/DafnyRef/Specifications.md
  docs/DafnyRef/Statements.md
  docs/DafnyRef/Types.md
  docs/DafnyRef/UserGuide.md
Labels: enhancement, documentation
