Repository dafny-lang/dafny, pull requests merged in 2022-09, with the labels that each got.

#2695 Add missing qualifier in publish step
  .github/workflows/publish-release-reusable.yml
Labels: run-deep-tests

#2704 fix: Pin Rouge version when building the manual
  .github/workflows/refman.yml
  RELEASE_NOTES.md
Labels: run-deep-tests

#2745 Solution to issue 2265 related to erroneous substitution under bindin…
  RELEASE_NOTES.md
  Source/DafnyCore/Substituter.cs
  Test/git-issues/git-issue-2265.dfy
  Test/git-issues/git-issue-2265.dfy.expect
Labels: kind: bug, part: verifier, status: needs-expert

#2824 Fix missing assembly version for the language server
  Source/DafnyLanguageServer/DafnyLanguageServer.csproj
Labels: severity: release-blocker
