Repository dafny-lang/dafny, pull requests merged in 2022-06, with the labels that each got.

#2192 chore: Slowness hints tests to be more robust.
  Source/DafnyLanguageServer.Test/Lookup/HoverVerificationTest.cs
Labels: kind: cleanup, part: lsp, kind: development-speed, kind: instability, difficulty: easy

#2209 Hotfix: Garbage collect z3 instances
  Source/DafnyLanguageServer/Language/DafnyProgramVerifier.cs
Labels: area: performance, kind: development-speed, severity: release-blocker

#2208 fix: Hotfix: {:opaque} crashing LSP when gutter icons are activated
  Source/DafnyLanguageServer.Test/Synchronization/DiagnosticsTest.cs
  Source/DafnyLanguageServer/Workspace/VerificationProgressReporter.cs
Labels: kind: bug, part: language server, severity: release-blocker

#2166 Feat: Plugin's Compiler/Verification errors should not prevent verification from running.
  Source/Dafny/DafnyMain.cs
  Source/Dafny/Reporting.cs
  Source/Dafny/Resolver.cs
  Source/DafnyLanguageServer.Test/Unit/DafnyLangSymbolResolverTest.cs
  Source/DafnyLanguageServer.Test/Unit/ParserExceptionTest.cs
  Source/DafnyLanguageServer.Test/Various/PluginsTestWithVerification.cs
  Source/DafnyLanguageServer.Test/_plugins/PluginsTest.cs
  Source/DafnyLanguageServer.Test/_plugins/PluginsTestVerification.cs
  Source/DafnyLanguageServer/Language/DiagnosticErrorReporter.cs
  Source/DafnyLanguageServer/Language/Symbols/DafnyLangSymbolResolver.cs
  Source/DafnyLanguageServer/Language/Symbols/ISymbolResolver.cs
  Source/DafnyLanguageServer/Language/Symbols/SymbolTableFactory.cs
  Source/DafnyLanguageServer/Workspace/DafnyDocument.cs
  Source/DafnyLanguageServer/Workspace/DocumentDatabase.cs
  Source/DafnyLanguageServer/Workspace/TextDocumentLoader.cs
  Source/DafnyPipeline.Test/PluginsTest.cs
  Source/DafnyPipeline.Test/_plugins/rewriterAllowingVerification.cs
  Source/DafnyPipeline.Test/_plugins/rewriterPreventingVerification.cs
  Source/DafnyPipeline.Test/_plugins/rewriterPreventingVerificationWithArgument.cs
  Source/DafnyPipeline.Test/_plugins/secondPlugin.cs
Labels: kind: enhancement, part: resolver, part: language server

#2204 Add a script to download all releases
  Scripts/download_all_releases.py
Labels: kind: development-speed

#2242 Hotfix: Copy the DafnyLanguageServer.dll
  Source/DafnyLanguageServer/DafnyLanguageServer.csproj
Labels: kind: development-speed, severity: release-blocker

#2251 Chore: Newest methods to debug assertions
  docs/DafnyRef/UserGuide.md
Labels: kind: enhancement, part: documentation

#2304 temporary: Target older windows version
  .github/workflows/integration-tests-reusable.yml
Labels: run-deep-tests

#2310 Use canonical path where needed when handling includes
  Source/Dafny/DafnyMain.cs
Labels: run-deep-tests
