Repository dafny-lang/dafny, pull requests merged in 2023-08, with the labels that each got.

#4381 Fix z3 download
  Makefile
  Scripts/package.py
Labels: run-deep-tests

#4392 [Counterexamples] Fix stack overflow during counterexample extraction for some programs
  Source/DafnyLanguageServer.Test/Various/CounterExampleTest.cs
  Source/DafnyLanguageServer/CounterExampleGeneration/DafnyModel.cs
  docs/dev/news/4392.fix
Labels: part: counterexamples

#4457 Fixed Windows workflow path
  .github/workflows/integration-tests-reusable.yml
Labels: run-deep-tests

#4455 Editting 3 links in the reference manual for pandoc to work with late…
  Source/DafnyCore/Feature.cs
  docs/DafnyRef/Expressions.md
  docs/DafnyRef/Features.md
  docs/DafnyRef/UserGuide.md
Labels: run-deep-tests

#4419 Improve performance for large projects
  Source/DafnyCore.Test/NodeTests.cs
  Source/DafnyCore.Test/WriterFromOutputHelper.cs
  Source/DafnyCore/DafnyFile.cs
  Source/DafnyCore/Options/DafnyProject.cs
  Source/DafnyDriver/DafnyDoc.cs
  Source/DafnyLanguageServer.Test/DafnyLanguageServer.Test.csproj
  Source/DafnyLanguageServer.Test/DafnyLanguageServerTestBase.cs
  Source/DafnyLanguageServer.Test/Performance/LargeFilesTest.cs
  Source/DafnyLanguageServer.Test/ProjectFiles/ProjectFilesTest.cs
  Source/DafnyLanguageServer.Test/StandaloneServerTest.cs
  Source/DafnyLanguageServer.Test/Synchronization/DiagnosticsTest.cs
  Source/DafnyLanguageServer.Test/Unit/GhostStateDiagnosticCollectorTest.cs
  Source/DafnyLanguageServer.Test/Unit/TextDocumentLoaderTest.cs
  Source/DafnyLanguageServer.Test/Util/ClientBasedLanguageServerTest.cs
  Source/DafnyLanguageServer.Test/Util/Stringify.cs
  Source/DafnyLanguageServer.Test/Util/TestNotificationReceiver.cs
  Source/DafnyLanguageServer.Test/Various/ExceptionTests.cs
  Source/DafnyLanguageServer/DafnyLanguageServer.cs
  Source/DafnyLanguageServer/Language/CachingParser.cs
  Source/DafnyLanguageServer/Language/IVerificationProgressReporter.cs
  Source/DafnyLanguageServer/Language/LanguageServerExtensions.cs
  Source/DafnyLanguageServer/ServerCommand.cs
  Source/DafnyLanguageServer/Workspace/CompilationManager.cs
  Source/DafnyLanguageServer/Workspace/Documents/Compilation.cs
  Source/DafnyLanguageServer/Workspace/Documents/CompilationAfterParsing.cs
  Source/DafnyLanguageServer/Workspace/Documents/CompilationAfterResolution.cs
  Source/DafnyLanguageServer/Workspace/ITextDocumentLoader.cs
  Source/DafnyLanguageServer/Workspace/IdeState.cs
  Source/DafnyLanguageServer/Workspace/IdeStateObserver.cs
  Source/DafnyLanguageServer/Workspace/ProjectManager.cs
  Source/DafnyLanguageServer/Workspace/TextDocumentLoader.cs
  Source/DafnyLanguageServer/Workspace/VerificationProgressReporter.cs
  Source/DafnyPipeline.Test/DafnyPipeline.Test.csproj
  Source/DafnyPipeline.Test/DocstringTest.cs
  Source/DafnyPipeline.Test/FormatterBaseTest.cs
  Source/DafnyPipeline.Test/IntraMethodVerificationStability.cs
  Source/DafnyPipeline.Test/Issue1355.cs
  Source/DafnyPipeline.Test/PluginsTest.cs
  Source/DafnyPipeline.Test/RelativePaths.cs
  Source/DafnyPipeline.Test/Trivia.cs
  Source/DafnyPipeline.Test/WriterFromOutputHelper.cs
  Source/DafnyTestGeneration.Test/BasicTypes.cs
  Source/DafnyTestGeneration.Test/Collections.cs
  Source/DafnyTestGeneration.Test/DafnyTestGeneration.Test.csproj
  Source/DafnyTestGeneration.Test/ShortCircuitRemoval.cs
  Source/DafnyTestGeneration.Test/Various.cs
Labels: severity: release-blocker

#4496 Revert change to Z3 path used by integration tests
  Source/IntegrationTests/LitTests.cs
  Test/dafny0/ConcurrentAttribute.dfy
Labels: run-deep-tests
